{
 "title": "Klever-Dash",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "klv_start_time / 1000000 / 60" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_peer_type" }
   ]
  },
  {
   "title": "Node Rating %",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Rating" }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_epoch_number", "legendFormat": "Current Epoch" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_is_syncing" }
   ]
  },
  {
   "title": "Klever Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image=\"kleverapp/klever-go-testnet:latest\"}"
    }
   ]
  },
  {
   "title": "Total Validator Blocks (Since DB Reload)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_leader", "legendFormat": "Proposed Blocks" },
    { "expr": "klv_count_accepted_blocks", "legendFormat": "Accepted Blocks" }
   ]
  },
  {
   "title": "Total Validator Leader Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "TotalNumLeaderSuccess" }
   ]
  },
  {
   "title": "Validator Signed / Accepted Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_consensus", "legendFormat": "Validator Signed" },
    {
     "expr": "klv_count_consensus_accepted_blocks",
     "legendFormat": "Validator Accepted"
    }
   ]
  },
  {
   "title": "Validator Produced Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorSuccess + TotalNumLeaderSuccess"
    }
   ]
  },
  {
   "title": "Total Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "TotalNumLeaderFailure" }
   ]
  },
  {
   "title": "Total Validator Ignored Signatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorIgnoredSignatures"
    }
   ]
  },
  {
   "title": "Complete Status of all Klever Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "elected_nodes", "legendFormat": "Elected" },
    { "expr": "eligible_nodes", "legendFormat": "Eligible" },
    { "expr": "jailed_nodes", "legendFormat": "Jailed" },
    { "expr": "waiting_nodes", "legendFormat": "Waiting" }
   ]
  },
  {
   "title": "Connected Nodes / Peers / Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_connected_nodes", "legendFormat": "Connected Nodes" },
    { "expr": "klv_num_connected_peers", "legendFormat": "Connected Peers" },
    { "expr": "klv_live_validator_nodes", "legendFormat": "Live Validators" },
    { "expr": "klv_num_validators", "legendFormat": "Epoch Validators" }
   ]
  },
  {
   "title": "TPS Peak",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_peak_tps", "legendFormat": "TX Peak" },
    { "expr": "klv_tx_pool_load", "legendFormat": "TX Pool Load" }
   ]
  },
  {
   "title": "Synced Slots / Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_highest_final_nonce", "legendFormat": "Block Height" },
    { "expr": "klv_probable_highest_nonce", "legendFormat": "Node Height" },
    { "expr": "klv_synchronized_slot", "legendFormat": "Node Slot" },
    { "expr": "klv_current_slot", "legendFormat": "Current Slot" }
   ]
  },
  {
   "title": "Slots / Epcoh  -  Seconds / Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_slots_per_epoch", "legendFormat": "Slots Per Epoch" },
    { "expr": "klv_slot_duration / 1000", "legendFormat": "Seconds Per Block" }
   ]
  },
  {
   "title": "Transaction Pool Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
   "targets": [
    { "expr": "klv_tx_pool_load" }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 2, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_mem_load_percent", "legendFormat": "Memory Usage %" },
    { "expr": "klv_cpu_load_percent", "legendFormat": "CPU Usage %" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 15 },
   "targets": [
    { "expr": "klv_mem_load_percent" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "klv_cpu_load_percent" }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{alias}} {{device}} write"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} transmit"
    }
   ]
  },
  {
   "title": "Processor usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  }
 ]
}