{
 "title": "Klever2Pi",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Validator Signed / Accepted Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_consensus", "legendFormat": "Signed" },
    {
     "expr": "klv_count_consensus_accepted_blocks",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Total Validator Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_leader", "legendFormat": "Proposed" },
    { "expr": "klv_count_accepted_blocks", "legendFormat": "Accepted" }
   ]
  },
  {
   "title": "Synced Slots",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_highest_final_nonce", "legendFormat": "Block Height" },
    { "expr": "klv_current_slot", "legendFormat": "Current Height " },
    { "expr": "klv_probable_highest_nonce", "legendFormat": "Node Height" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_is_syncing" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_peer_type" }
   ]
  },
  {
   "title": "Rating",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Rating" }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "TotalNumLeaderFailure" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AvailableBalance" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ClaimableRewards" }
   ]
  },
  {
   "title": "Transaction Pool Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "targets": [
    { "expr": "klv_tx_pool_load" }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 11, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_mem_load_percent", "legendFormat": "Memory Usage %" },
    { "expr": "klv_cpu_load_percent", "legendFormat": "CPU Usage %" }
   ]
  },
  {
   "title": "TX Pool",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_tx_pool_load" }
   ]
  }
 ]
}