{
 "title": "Validator Combined Personal",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "targets": [
    { "expr": "klv_start_time / 1000000 / 60" }
   ]
  },
  {
   "title": "Node Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_app_version", "legendFormat": "{{node_version}}" }
   ]
  },
  {
   "title": "Node Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_app_name", "legendFormat": "{{node_name}}" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_peer_type" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_peer_type" }
   ]
  },
  {
   "title": "Node Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_app_name", "legendFormat": "{{node_name}}" }
   ]
  },
  {
   "title": "Node Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_app_version", "legendFormat": "{{node_version}}" }
   ]
  },
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "targets": [
    { "expr": "klv_start_time / 1000000 / 60" }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image=\"kleverapp/klever-go:latest\"}"
    }
   ]
  },
  {
   "title": "Consensus Slot State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_slot_state" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_is_syncing" }
   ]
  },
  {
   "title": "Node Rating %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Rating" }
   ]
  },
  {
   "title": "Total Validator Ignored Signatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorIgnoredSignatures"
    }
   ]
  },
  {
   "title": "Total Validator Ignored Signatures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorIgnoredSignatures"
    }
   ]
  },
  {
   "title": "Node Rating %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Rating" }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_is_syncing" }
   ]
  },
  {
   "title": "Consensus Slot State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_slot_state" }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image=\"kleverapp/klever-go:latest\"}"
    }
   ]
  },
  {
   "title": "Synced Slots / Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_highest_final_nonce", "legendFormat": "Block Height" },
    { "expr": "klv_probable_highest_nonce", "legendFormat": "Node Height" },
    { "expr": "klv_synchronized_slot", "legendFormat": "Node Slot" },
    { "expr": "klv_current_slot", "legendFormat": "Current Slot" }
   ]
  },
  {
   "title": "Total Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_count_leader-klv_count_accepted_blocks"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_epoch_number", "legendFormat": "Current Epoch" }
   ]
  },
  {
   "title": "Total Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klv_count_leader-klv_count_accepted_blocks"
    }
   ]
  },
  {
   "title": "Synced Slots / Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_highest_final_nonce", "legendFormat": "Block Height" },
    { "expr": "klv_probable_highest_nonce", "legendFormat": "Node Height" },
    { "expr": "klv_synchronized_slot", "legendFormat": "Node Slot" },
    { "expr": "klv_current_slot", "legendFormat": "Current Slot" }
   ]
  },
  {
   "title": "Total Validator Blocks (Since DB Reload)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_leader", "legendFormat": "Proposed Blocks" },
    { "expr": "klv_count_accepted_blocks", "legendFormat": "Accepted Blocks" }
   ]
  },
  {
   "title": "Validator Signed / Accepted Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_consensus", "legendFormat": "Signed" },
    {
     "expr": "klv_count_consensus_accepted_blocks",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Validator Produced Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorSuccess + TotalNumLeaderSuccess"
    }
   ]
  },
  {
   "title": "Connected Nodes / Peers / Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_connected_nodes", "legendFormat": "Connected Nodes" },
    { "expr": "klv_num_connected_peers", "legendFormat": "Connected Peers" },
    { "expr": "klv_live_validator_nodes", "legendFormat": "Live Validators" },
    { "expr": "klv_num_validators", "legendFormat": "Epoch Validators" }
   ]
  },
  {
   "title": "Validator Produced Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "TotalNumValidatorSuccess + TotalNumLeaderSuccess"
    }
   ]
  },
  {
   "title": "Validator Signed / Accepted Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_consensus", "legendFormat": "Signed" },
    {
     "expr": "klv_count_consensus_accepted_blocks",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Total Validator Blocks (Since DB Reload)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_count_leader", "legendFormat": "Proposed Blocks" },
    { "expr": "klv_count_accepted_blocks", "legendFormat": "Accepted Blocks" }
   ]
  },
  {
   "title": "Transaction Pool Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 15 },
   "targets": [
    { "expr": "klv_tx_pool_load" }
   ]
  },
  {
   "title": "Complete Status of all Klever Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "elected_nodes", "legendFormat": "Elected" },
    { "expr": "eligible_nodes", "legendFormat": "Eligible" },
    { "expr": "jailed_nodes", "legendFormat": "Jailed" },
    { "expr": "waiting_nodes", "legendFormat": "Waiting" },
    { "expr": "inactive_nodes", "legendFormat": "Inactive" }
   ]
  },
  {
   "title": "Transaction Pool Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 15 },
   "targets": [
    { "expr": "klv_tx_pool_load" }
   ]
  },
  {
   "title": "Delegated KLV",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stake_total" }
   ]
  },
  {
   "title": "Delegated KLV",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stake_total" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 24 },
   "targets": [
    { "expr": "klv_cpu_load_percent" }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 2, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_mem_load_percent", "legendFormat": "Memory Usage %" },
    { "expr": "klv_cpu_load_percent", "legendFormat": "CPU Usage %" }
   ]
  },
  {
   "title": "Pool #1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_tx_pool_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 2, "x": 13, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_mem_load_percent", "legendFormat": "Memory Usage %" },
    { "expr": "klv_cpu_load_percent", "legendFormat": "CPU Usage %" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 24 },
   "targets": [
    { "expr": "klv_cpu_load_percent" }
   ]
  },
  {
   "title": "Pool #2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_tx_pool_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TPS Peak",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "klv_peak_tps", "legendFormat": "TX Peak" }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} transmit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AvailableBalance", "legendFormat": "Available Balance (KLV)" },
    { "expr": "CalcBalance", "legendFormat": "Balance in USD" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "AvailableBalance", "legendFormat": "Available Balance (KLV)" },
    { "expr": "CalcBalance", "legendFormat": "Balance in USD" }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 33 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "{{alias}} {{device}} transmit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "KLVPrice", "legendFormat": "KLV (USD)" }
   ]
  }
 ]
}